-- Schema local equivalente ao PostgreSQL remoto (Neon).
-- O banco remoto e a fonte de verdade; este arquivo serve para testes locais.

CREATE TABLE IF NOT EXISTS company (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    cnpj VARCHAR,
    address VARCHAR
);

CREATE TABLE IF NOT EXISTS cooperative (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    cnpj VARCHAR,
    latitude NUMERIC,
    longitude NUMERIC,
    average_rating NUMERIC,
    specialties VARCHAR
);

CREATE TABLE IF NOT EXISTS waste_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR,
    description VARCHAR,
    default_risk_level VARCHAR
);

CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER REFERENCES company(id),
    name VARCHAR,
    email VARCHAR,
    password_hash VARCHAR,
    role VARCHAR,
    user_type VARCHAR
);

CREATE TABLE IF NOT EXISTS area (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER REFERENCES company(id),
    sector_name VARCHAR,
    location_description VARCHAR
);

CREATE TABLE IF NOT EXISTS incident (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER REFERENCES company(id),
    user_id INTEGER REFERENCES "user"(id),
    area_id INTEGER REFERENCES area(id),
    waste_type_id INTEGER REFERENCES waste_type(id),
    photo_url VARCHAR,
    employee_description TEXT,
    contamination_level VARCHAR,
    estimated_quantity NUMERIC,
    priority VARCHAR,
    status VARCHAR,
    registered_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_report (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER REFERENCES incident(id),
    detected_waste_type VARCHAR,
    ai_contamination_level VARCHAR,
    recommendations TEXT,
    report_text TEXT,
    generated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attachment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER REFERENCES incident(id),
    file_url VARCHAR,
    file_type VARCHAR
);

CREATE TABLE IF NOT EXISTS collection (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER REFERENCES incident(id),
    cooperative_id INTEGER REFERENCES cooperative(id),
    request_date TIMESTAMP,
    scheduled_date TIMESTAMP,
    current_status VARCHAR,
    collection_type VARCHAR,
    urgent BOOLEAN
);

CREATE TABLE IF NOT EXISTS collection_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INTEGER REFERENCES collection(id),
    status VARCHAR,
    change_date TIMESTAMP,
    observation TEXT
);

CREATE TABLE IF NOT EXISTS conversation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER REFERENCES company(id),
    cooperative_id INTEGER REFERENCES cooperative(id),
    collection_id INTEGER REFERENCES collection(id),
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER REFERENCES conversation(id),
    user_id INTEGER REFERENCES "user"(id),
    text TEXT,
    reported BOOLEAN,
    sent_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message_attachment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER REFERENCES message(id),
    file_url VARCHAR,
    file_type VARCHAR
);

CREATE TABLE IF NOT EXISTS notification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES "user"(id),
    type VARCHAR,
    title VARCHAR,
    message TEXT,
    read BOOLEAN,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cooperative_id INTEGER REFERENCES cooperative(id),
    user_id INTEGER REFERENCES "user"(id),
    collection_id INTEGER REFERENCES collection(id),
    stars INTEGER,
    comment TEXT,
    review_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS esg_metric (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER REFERENCES company(id),
    period VARCHAR,
    total_waste_kg NUMERIC,
    total_recycled_kg NUMERIC,
    recycling_percentage NUMERIC,
    calculated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_incident_company_registered_at ON incident (company_id, registered_at DESC);
CREATE INDEX IF NOT EXISTS idx_incident_area_registered_at ON incident (area_id, registered_at ASC);
CREATE INDEX IF NOT EXISTS idx_esg_metric_company_period ON esg_metric (company_id, period);
CREATE INDEX IF NOT EXISTS idx_collection_incident ON collection (incident_id);
CREATE INDEX IF NOT EXISTS idx_collection_cooperative ON collection (cooperative_id);
