name: Build chatbot image

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente da imagem
        required: true
        type: choice
        default: qa
        options: [qa, prod]

jobs:
  build-on-push:
    if: github.event_name == 'push'
    uses: app-volta/volta-devops/.github/workflows/reusable-docker-build-push.yaml@main
    with:
      image-name: chatbot
      environment: qa
      context: .
      dockerfile: ./Dockerfile
      push: true
      notify-devops: false

  build-manual:
    if: github.event_name == 'workflow_dispatch'
    uses: app-volta/volta-devops/.github/workflows/reusable-docker-build-push.yaml@main
    with:
      image-name: chatbot
      environment: ${{ inputs.environment }}
      context: .
      dockerfile: ./Dockerfile
      push: true
      notify-devops: false
